// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipyhydcaqchcioqjasnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlweWh5ZGNhcWNoY2lvcWphc256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjIwMTgsImV4cCI6MjA2NDM5ODAxOH0.2dEYMFj3WzmJV16P00hx2zBKeaTfe5gzx-RA3X19xKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);