// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgztbuckqbxrhqcxvcrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nenRidWNrcWJ4cmhxY3h2Y3JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0ODgxODIsImV4cCI6MjA1NzA2NDE4Mn0.C4cS_IKhsJ9EpG0mHQFzMxIZOw3AhfCzcV0GvZRF6lw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);